version: '3'

services :
    nginx:
        container_name: nginx
        image: nginx:nginx
        build: ./requirements/nginx/
        ports:
            - "443:443"
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - nginx_press_data:/var/www/html
    mariadb:
        image: mariadb:mariadb
        container_name: mariadb
        build: ./requirements/mariadb/
        ports:
            - "3306:3306"
        restart: unless-stopped
        env_file:
            - .env
    wordpress:
        image: wordpress:wordpress
        container_name: wordpress
        build: ./requirements/wordpress/
        ports:
            - "9000:9000"
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - mariadb
            - nginx
        volumes:
            - nginx_press_data:/mnt/shared_nginx_press/wordpress

volumes:
  database_data:
    driver: local
    driver_opts:
      type: none
      device: $HOME/Desktop/Inception/database_data
      o: bind
  nginx_press_data:
    driver_opts:
      type: none
      device: $HOME/Desktop/Inception/nginx_press_data
      o: bind
      